name: CLI Game Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test-cli-functionality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build package
      run: npm run build

    - name: Run All CLI Tests
      run: npm test

    - name: Test CLI Complete Game Functionality
      run: npm run test:complete-game

    - name: Run All Tests
      run: npm run test:all

  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Verify package integrity
      run: |
        echo "Verifying package structure..."
        test -f "package.json" || (echo "❌ package.json missing" && exit 1)
        test -f "bin/swordfight.js" || (echo "❌ bin/swordfight.js missing" && exit 1)
        test -d "lib" || (echo "❌ lib directory missing" && exit 1)
        echo "✅ Package structure verified"
